apiVersion: openedge.dev/v1
kind: Meta
org: u_user_3H95oVoJTbx8kk9w3t70NhZA6bw
name: u_user_3H95oVoJTbx8kk9w3t70NhZA6bw
plan: pro
region: san-jose
projectCount: 2
generatedAt: "2026-08-23T17:15:08.520Z"
managedBy: OpenEdge GitOps
